/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MedicoController;
import Controller.PlanoDeSaudeController;
import Controller.UsuarioController;
import java.sql.SQLException;

/**
 *
 * @author Danilo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        panelPrincipal = new javax.swing.JPanel();
        menuBarPrincipal = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        menuItemCadUsuario = new javax.swing.JMenuItem();
        menuItemCadPaciente = new javax.swing.JMenuItem();
        menuItemCadMedico = new javax.swing.JMenuItem();
        menuItemCadPlanoSaude = new javax.swing.JMenuItem();
        menuItemCadConsulta = new javax.swing.JMenuItem();
        menuItemCadPerfil = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuItemRelUsuarios = new javax.swing.JMenuItem();
        menuItemRelMedicos = new javax.swing.JMenuItem();
        menuItemRelPlano = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        menuCadastrar.setText("Cadastrar");
        menuCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuItemCadUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCadUsuario.setText("Usuário");
        menuItemCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadUsuarioActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadUsuario);

        menuItemCadPaciente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCadPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastrar_paciente.png"))); // NOI18N
        menuItemCadPaciente.setText("Paciente");
        menuItemCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadPacienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadPaciente);

        menuItemCadMedico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCadMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastrar_medicos.png"))); // NOI18N
        menuItemCadMedico.setText("Médico");
        menuItemCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadMedicoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadMedico);

        menuItemCadPlanoSaude.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCadPlanoSaude.setText("Plano de Saúde");
        menuItemCadPlanoSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadPlanoSaudeActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadPlanoSaude);

        menuItemCadConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCadConsulta.setText("Consulta");
        menuItemCadConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadConsultaActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadConsulta);

        menuItemCadPerfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCadPerfil.setText("Perfil");
        menuItemCadPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadPerfilActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadPerfil);

        menuBarPrincipal.add(menuCadastrar);

        menuRelatorios.setText("Relatórios");
        menuRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatoriosActionPerformed(evt);
            }
        });

        menuItemRelUsuarios.setText("Relatório de Usuários");
        menuItemRelUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelUsuariosActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuItemRelUsuarios);

        menuItemRelMedicos.setText("Relatório de Médicos");
        menuItemRelMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelMedicosActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuItemRelMedicos);

        menuItemRelPlano.setText("Relatório de Planos de Saúde");
        menuItemRelPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelPlanoActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuItemRelPlano);

        menuBarPrincipal.add(menuRelatorios);

        menuSair.setText("Sair");
        menuSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuBarPrincipal.add(menuSair);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCadPlanoSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadPlanoSaudeActionPerformed
        
        //Fecha a tela que está sendo mostrada
        dispose();
        
        try {
            //Tela que se quer abrir
            TelaCadastroPlanoDeSaude telaCadastroPlanoDeSaude = new TelaCadastroPlanoDeSaude();
            
            //Torna a tela vísivel 
            telaCadastroPlanoDeSaude.setVisible(true);

            //Coloca a tela que está sendo aberta no centro da tela/monitor
            telaCadastroPlanoDeSaude.setLocationRelativeTo(null);
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_menuItemCadPlanoSaudeActionPerformed

    private void menuItemCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadPacienteActionPerformed
        
        //Fecha a tela que está sendo mostrada
        dispose();
        
        try {
            //Tela que se quer abrir
            TelaCadastroPaciente telaCadastroPaciente = new TelaCadastroPaciente();
            
            //Torna a tela vísivel 
            telaCadastroPaciente.setVisible(true);

            //Coloca a tela que está sendo aberta no centro da tela/monitor
            telaCadastroPaciente.setLocationRelativeTo(null);
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_menuItemCadPacienteActionPerformed

    private void menuItemCadConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadConsultaActionPerformed
        
        //Fecha a tela que está sendo mostrada
        dispose();
        
        try {
            //Tela que se quer abrir
            TelaCadastroConsulta telaCadastroConsulta = new TelaCadastroConsulta();
            
            //Torna a tela vísivel 
            telaCadastroConsulta.setVisible(true);

            //Coloca a tela que está sendo aberta no centro da tela/monitor
            telaCadastroConsulta.setLocationRelativeTo(null);
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_menuItemCadConsultaActionPerformed

    private void menuItemCadPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadPerfilActionPerformed
        
        //Fecha a tela que está sendo mostrada
        dispose();
        
        //Tela que se quer abrir
        //TelaCadastroPerfil telaCadastroPerfil = new TelaCadastroPerfil();
        
        //Torna a tela vísivel 
        //telaCadastroPerfil.setVisible(true);
        
        //Coloca a tela que está sendo aberta no centro da tela/monitor
        //telaCadastroPerfil.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_menuItemCadPerfilActionPerformed

    private void menuItemCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadUsuarioActionPerformed
        
        //Fecha a tela que está sendo mostrada
        dispose();
        
        try {
            //Tela que se quer abrir
            TelaCadastroUsuario telaCadastroUsuario = new TelaCadastroUsuario();
            
            //Torna a tela vísivel
            telaCadastroUsuario.setVisible(true);
        
            //Coloca a tela que está sendo aberta no centro da tela/monitor
            telaCadastroUsuario.setLocationRelativeTo(null);
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
        
        
    }//GEN-LAST:event_menuItemCadUsuarioActionPerformed

    private void menuItemCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadMedicoActionPerformed
        
        //Fecha a tela que está sendo mostrada
        dispose();
        
        try {
            //Tela que se quer abrir
            TelaCadastroMedico telaCadastroMedico = new TelaCadastroMedico();
            
            //Torna a tela vísivel
            telaCadastroMedico.setVisible(true);

            //Coloca a tela que está sendo aberta no centro da tela/monitor
            telaCadastroMedico.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_menuItemCadMedicoActionPerformed

    private void menuItemRelUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelUsuariosActionPerformed
        
        UsuarioController usuarioController = new UsuarioController();
        
        usuarioController.gerarRelatorioUsuario();
        
    }//GEN-LAST:event_menuItemRelUsuariosActionPerformed

    private void menuItemRelMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelMedicosActionPerformed
        MedicoController medicoController = new MedicoController();
        medicoController.gerarRelatorioMedico();
    }//GEN-LAST:event_menuItemRelMedicosActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        
        new TelaLogin().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        
        new TelaLogin().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatoriosActionPerformed
        
    }//GEN-LAST:event_menuRelatoriosActionPerformed

    private void menuItemRelPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelPlanoActionPerformed
        PlanoDeSaudeController planoDeSaudeController = new PlanoDeSaudeController();
        
        try {
            planoDeSaudeController.gerarRelatorioPlanoDeSaude();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_menuItemRelPlanoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuItemCadConsulta;
    private javax.swing.JMenuItem menuItemCadMedico;
    private javax.swing.JMenuItem menuItemCadPaciente;
    private javax.swing.JMenuItem menuItemCadPerfil;
    private javax.swing.JMenuItem menuItemCadPlanoSaude;
    private javax.swing.JMenuItem menuItemCadUsuario;
    private javax.swing.JMenuItem menuItemRelMedicos;
    private javax.swing.JMenuItem menuItemRelPlano;
    private javax.swing.JMenuItem menuItemRelUsuarios;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
