/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UsuarioController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Danilo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemCadUsuario = new javax.swing.JMenuItem();
        menuItemCadPaciente = new javax.swing.JMenuItem();
        menuItemCadMedico = new javax.swing.JMenuItem();
        menuItemCadPlanoSaude = new javax.swing.JMenuItem();
        menuItemCadConsulta = new javax.swing.JMenuItem();
        menuItemCadPerfil = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastrar");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuItemCadUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCadUsuario.setText("Usuário");
        menuItemCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCadUsuario);

        menuItemCadPaciente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCadPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastrar_paciente.png"))); // NOI18N
        menuItemCadPaciente.setText("Paciente");
        menuItemCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadPacienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCadPaciente);

        menuItemCadMedico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCadMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastrar_medicos.png"))); // NOI18N
        menuItemCadMedico.setText("Médico");
        menuItemCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadMedicoActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCadMedico);

        menuItemCadPlanoSaude.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCadPlanoSaude.setText("Plano de Saúde");
        menuItemCadPlanoSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadPlanoSaudeActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCadPlanoSaude);

        menuItemCadConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCadConsulta.setText("Consulta");
        menuItemCadConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCadConsulta);

        menuItemCadPerfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCadPerfil.setText("Perfil");
        menuItemCadPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadPerfilActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCadPerfil);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem1.setText("Relatório de Usuários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCadPlanoSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadPlanoSaudeActionPerformed
        
        //Fecha a tela que está sendo mostrada
        dispose();
        
        try {
            //Tela que se quer abrir
            TelaCadastroPlanoDeSaude telaCadastroPlanoDeSaude = new TelaCadastroPlanoDeSaude();
            
            //Torna a tela vísivel 
            telaCadastroPlanoDeSaude.setVisible(true);

            //Coloca a tela que está sendo aberta no centro da tela/monitor
            telaCadastroPlanoDeSaude.setLocationRelativeTo(null);
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_menuItemCadPlanoSaudeActionPerformed

    private void menuItemCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadPacienteActionPerformed
        
        //Fecha a tela que está sendo mostrada
        dispose();
        
        try {
            //Tela que se quer abrir
            TelaCadastroPaciente telaCadastroPaciente = new TelaCadastroPaciente();
            
            //Torna a tela vísivel 
            telaCadastroPaciente.setVisible(true);

            //Coloca a tela que está sendo aberta no centro da tela/monitor
            telaCadastroPaciente.setLocationRelativeTo(null);
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_menuItemCadPacienteActionPerformed

    private void menuItemCadConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadConsultaActionPerformed
        
        //Fecha a tela que está sendo mostrada
        dispose();
        
        try {
            //Tela que se quer abrir
            TelaCadastroConsulta telaCadastroConsulta = new TelaCadastroConsulta();
            
            //Torna a tela vísivel 
            telaCadastroConsulta.setVisible(true);

            //Coloca a tela que está sendo aberta no centro da tela/monitor
            telaCadastroConsulta.setLocationRelativeTo(null);
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_menuItemCadConsultaActionPerformed

    private void menuItemCadPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadPerfilActionPerformed
        
        //Fecha a tela que está sendo mostrada
        dispose();
        
        //Tela que se quer abrir
        //TelaCadastroPerfil telaCadastroPerfil = new TelaCadastroPerfil();
        
        //Torna a tela vísivel 
        //telaCadastroPerfil.setVisible(true);
        
        //Coloca a tela que está sendo aberta no centro da tela/monitor
        //telaCadastroPerfil.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_menuItemCadPerfilActionPerformed

    private void menuItemCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadUsuarioActionPerformed
        
        //Fecha a tela que está sendo mostrada
        dispose();
        
        try {
            //Tela que se quer abrir
            TelaCadastroUsuario telaCadastroUsuario = new TelaCadastroUsuario();
            
            //Torna a tela vísivel
            telaCadastroUsuario.setVisible(true);
        
            //Coloca a tela que está sendo aberta no centro da tela/monitor
            telaCadastroUsuario.setLocationRelativeTo(null);
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
        
        
    }//GEN-LAST:event_menuItemCadUsuarioActionPerformed

    private void menuItemCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadMedicoActionPerformed
        
        //Fecha a tela que está sendo mostrada
        dispose();
        
        try {
            //Tela que se quer abrir
            TelaCadastroMedico telaCadastroMedico = new TelaCadastroMedico();
            
            //Torna a tela vísivel
            telaCadastroMedico.setVisible(true);

            //Coloca a tela que está sendo aberta no centro da tela/monitor
            telaCadastroMedico.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_menuItemCadMedicoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        UsuarioController usuarioController = new UsuarioController();
        
        usuarioController.gerarRelatorioUsuario();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuItemCadConsulta;
    private javax.swing.JMenuItem menuItemCadMedico;
    private javax.swing.JMenuItem menuItemCadPaciente;
    private javax.swing.JMenuItem menuItemCadPerfil;
    private javax.swing.JMenuItem menuItemCadPlanoSaude;
    private javax.swing.JMenuItem menuItemCadUsuario;
    // End of variables declaration//GEN-END:variables
}
